// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBafzPmQHZmzC91p09U099q0t0aryitFp0',
    appId: '1:948955471427:web:a8f3a39a3b92c0865bfef6',
    messagingSenderId: '948955471427',
    projectId: 'uas-mobile2-9fcd1',
    authDomain: 'uas-mobile2-9fcd1.firebaseapp.com',
    storageBucket: 'uas-mobile2-9fcd1.appspot.com',
    measurementId: 'G-SB2P0CWC86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYUwoTDqJNNPXOKkSnD334IA6hi8t80wE',
    appId: '1:948955471427:android:4f4bf429397e37e65bfef6',
    messagingSenderId: '948955471427',
    projectId: 'uas-mobile2-9fcd1',
    storageBucket: 'uas-mobile2-9fcd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-dYWIcDl7pJvIw53L_mSPrNrXiTpWDRA',
    appId: '1:948955471427:ios:237345980c43433c5bfef6',
    messagingSenderId: '948955471427',
    projectId: 'uas-mobile2-9fcd1',
    storageBucket: 'uas-mobile2-9fcd1.appspot.com',
    iosBundleId: 'com.example.uasmobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-dYWIcDl7pJvIw53L_mSPrNrXiTpWDRA',
    appId: '1:948955471427:ios:3f3cebb514b63d365bfef6',
    messagingSenderId: '948955471427',
    projectId: 'uas-mobile2-9fcd1',
    storageBucket: 'uas-mobile2-9fcd1.appspot.com',
    iosBundleId: 'com.example.uasmobile2.RunnerTests',
  );
}
